export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_MAP_SUCCESS = "LOAD_MAP_SUCCESS";
export const LOAD_PROCESS_MAP_SUCCESS = "LOAD_PROCESS_MAP_SUCCESS";
export const LOAD_PROCESS_MAP_FAILED = "LOAD_PROCESS_MAP_FAILED";
export const UPDATE_MAP_SUCCESS = "UPDATE_MAP_SUCCESS";
export const UPDATE_STEP_SUCCESS = "UPDATE_STEP_SUCCESS";
export const SAVE_MAP_SUCCESS = "SAVE_MAP_SUCCESS";
export const ADD_STEP_SUCCESS = "ADD_STEP_SUCCESS";

export const LOAD_LOCALIZED_DATA_SUCCESS = "LOAD_LOCALIZED_DATA_SUCCESS";
export const LOAD_LOCALIZED_DATA_FAILED = "LOAD_LOCALIZED_DATA_FAILED";

export const NAV_SELECTION_SUCCESS2 = "NAV_SELECTION_SUCCESS";
